name: PokeRadar
description: The best app to raid in Pokémon GO
full_description: 'Get your first raid finished in a few minutes. Download the app, setup your profile and you are ready to host a raid or join one remotely!<br>
PokeRadar is the simplest way to find raids or help to beat a raid at your place! It's a Pokémon GO companion app.<br>
<br>
This app is perfect for you if:<br>
- You don't have a community to be able to take down legendary or mega raids ? PokeRadar is made for you, host a raid and find people to invite so you can beat the boss easily!<br>
- You want to grind a hundo or shiny ? Use PokeRadar to join raids in a few minutes. Get your passes ready !<br>
- Hundo hunter, see the boss perfect CP directly in the room, easy to know if it's hundo or 98%<br>
- You want all the regionals ! Even in shiny! Azelf, Mesprit, Uxie, all forms of Tatsugiri, Mr Mime, and all other regionals can be easily found in PokeRadar, when available in game. You don't need to travel, just join a remote raid and you're done<br>
<br>
- GIGAMAX ROOMS: you can have a room with 20 users, so it's easier to beat the boss. 5 or 10 people won't be enough. You can also set the minimum level so that you have 20 strong trainers and the gigamax boss will be easy to beat<br>
<br>
I am a player of PoGo and I made the app by myself, a lot more features are coming.<br><br>
Privacy:<br>
I am very concerned about security and privacy, and this app doesn't track anything, your data is fully on-device and nothing about your personal data is stored.<br>
If you have any request or suggestion you can contact me through the contact support button in-app.<br>
Download the app and stay tuned for updates !<br><br>
Privacy policy: https://www.freeprivacypolicy.com/live/c92a2664-af59-48ee-a619-fd5f73727f5d<br>
Terms of service: https://www.apple.com/legal/internet-services/itunes/dev/stdeula/<br>
'
iOS: https://apps.apple.com/app/id6764646757
web: https://pokeradar.app
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png